### ISSUE TITLE
Invalid or unsupported zip format. No END header found

### ISSUE THREAD

**Issue by deeperton** [pose/webdriver-manager#1]
```
Linux namePC 3.11.0-12-generic #19-Ubuntu SMP Wed Oct 9 16:20:46 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ webdriver-manager update
Updating selenium standalone
downloading http://selenium-release.storage.googleapis.com/2.42/selenium-server-standalone-2.42.2.jar...
Updating chromedriver
downloading https://chromedriver.storage.googleapis.com/2.10/chromedriver_linux64.zip...
selenium-server-standalone-2.42.2.jar downloaded to /usr/local/lib/node_modules/protractor/selenium/selenium-server-standalone-2.42.2.jar
chromedriver_2.10.zip downloaded to /usr/local/lib/node_modules/protractor/selenium/chromedriver_2.10.zip

Invalid or unsupported zip format. No END header found
```

Then, try again
```
$ webdriver-manager update
selenium standalone is up to date.
chromedriver is up to date.
```
but folder `/usr/local/lib/node_modules/protractor/selenium/` doesn't contains `chromedriver`.

**Fix:** manual download and extract `chromedriver`.

**Comment by ictgtvt** [comment]
I had found the alternative download link here: http://chromedriver.storage.googleapis.com/index.html?path=2.10/

Download the suitable file: and extract it "chromedriver.exe" to:
[project]\node_modules\protractor\selenium\

**Comment by pose** [comment]
I've tried reproducing this issue in Windows and I'm not getting that error any more. Feel free to re-open if you are still facing this issue. Thanks!
