### ISSUE TITLE
Add support for downloading nw.js' Chromedriver

### ISSUE THREAD

**Issue by twolfson** [pose/webdriver-manager#13]
In https://github.com/nwjs/npm-installer/issues/23, we are discussing what repository best fits downloading nw.js' Chromedriver. It was recently mentioned that Selenium can take a custom path for both Chromedriver binary as well as Chrome binary. Would it be possible to add another download option for nw.js' Chromedriver?

**Comment by pose** [comment]
@twolfson Yes, definitely. We can add a new property here called `nw-chromedriver`: https://github.com/pose/webdriver-manager/blob/master/config.json#L3 . What do you think?

**Comment by twolfson** [comment]
Yea, I think that would work.

**Comment by gbmhunter** [comment]
Looks good.

**Comment by twolfson** [comment]
Awesome, thanks @pose. I will try it right out =)

**Comment by twolfson** [comment]
It looks like the latest release is installing `chromedriver` instead of `chromedriver-nw` =/

```bash
$ ./node_modules/.bin/webdriver-manager update --chromedriver-nw
Updating selenium standalone
downloading http://selenium-release.storage.googleapis.com/2.46/selenium-server-standalone-2.46.0.jar...
Updating chromedriver
downloading http://chromedriver.storage.googleapis.com/2.16/chromedriver_linux64.zip...
chromedriver_2.16.zip downloaded to /home/todd/github/plaidchat/node_modules/webdriver-manager/selenium/chromedriver_2.16.zip
/home/todd/github/plaidchat/node_modules/webdriver-manager/selenium/chromedriver_2.16.zip /home/todd/github/plaidchat/node_modules/webdriver-manager/selenium
selenium-server-standalone-2.46.0.jar downloaded to /home/todd/github/plaidchat/node_modules/webdriver-manager/selenium/selenium-server-standalone-2.46.0.jar
The following files were installed: /home/todd/github/plaidchat/node_modules/webdriver-manager/selenium/selenium-server-standalone-2.46.0.jar /home/todd/github/plaidchat/node_modules/webdriver-manager/selenium/chromedriver
```

**Comment by twolfson** [comment]
I found the issue and am opening a patch for it.
