### ISSUE TITLE
webdriver-manager update not working on independent install

### ISSUE THREAD

**Issue by stevejpurves** [pose/webdriver-manager#2]
I can't get webdriver-manager to work if installed independently from protractor. The latest version that i get with protractor works fine.

on independent installation I get a failure during update, and an error about "invalid or incompatible zip file" for the chrome driver. Update fails the first time. Subsequent updates report that both the standalone and chromedriver are up to date. Yet 'status' reports that both are not present.

Installing the latest protractor (1.3.0) and using webdriver-manager installed with that works fine. Should we be expecting an independent install to work at this stage?

**Comment by pose** [comment]
Tried running it on Windows and it works ok. Feel free to re-open if you are still facing this issue. Thanks!

**Comment by wolfdogg** [comment]
@stevejpurves, I too would like to do it via command line.  when i run `webdriver-manager`, or `webdriver-manager update` or `npm webdirver-manager update`  it doesnt understand the commands..  im not understanding the solution you guys came up with.  were you guys just calling it quits on the command line? cause i dev via my putty to my linux box.... deadlocked right now on this issue.

**Comment by pose** [comment]
Hi @wolfdogg, are you getting the same error after doing `npm i -g webdriver-manager`? It seems like you don't have it installed yet. Let's close this issue but feel free to open another if you are having issues updating webdriver bundles.
